Feature/update group buying order log
urfit-tech/lodestar-server pull request #13
Opened 2023-05-18 09:01 UTC by aniku777tw

2023-05-22 18:42 UTC, aniku777tw commented
![](https://github.trello.services/images/mini-trello-icon.png) [【團購】團購同行者可邀請非會員](https://trello.com/c/1mC3Fdj3/4372-%E3%80%90%E5%9C%98%E8%B3%BC%E3%80%91%E5%9C%98%E8%B3%BC%E5%90%8C%E8%A1%8C%E8%80%85%E5%8F%AF%E9%82%80%E8%AB%8B%E9%9D%9E%E6%9C%83%E5%93%A1)

2023-06-19 02:04 UTC, jackey8616 requested changes

2023-06-19 02:04 UTC, jackey8616 commented on src/order/order.controller.spec.ts
> +appSecret.value = 'testKey';
Use [this](https://github.com/urfit-tech/lodestar-server/blob/feature/update-group-buying-order-log/test/data.ts).

2023-06-19 02:04 UTC, jackey8616 commented on src/order/order.controller.spec.ts
> +  beforeAll(async () => {
Use `beforeEach` in order to clean datas in each cases.  
Then you can remove all 
  
```ts
await orderLogRepo.delete({});
await memberRepo.delete({});
```
  
in code.

2023-06-19 02:04 UTC, jackey8616 commented on src/order/order.controller.spec.ts
> +  afterAll(async () => {
`afterEach`.

2023-06-19 02:04 UTC, jackey8616 commented on src/order/order.controller.ts
> +      await verify(authorization.split(' ')[1], process.env.HASURA_JWT_SECRET);
process.env.HASURA_JWT_SECRET can use ConfigService to fetch.  
FYI: [AuthService](https://github.com/urfit-tech/lodestar-server/blob/feature/update-group-buying-order-log/src/auth/auth.service.ts#L18-L28).

2023-06-19 02:04 UTC, jackey8616 commented on src/order/order.controller.ts
> +      transferOrderToken = (await verify(token, process.env.HASURA_JWT_SECRET)) as TransferReceivedOrderToken;
FYI: [AuthService](https://github.com/urfit-tech/lodestar-server/blob/feature/update-group-buying-order-log/src/auth/auth.service.ts#L18-L28).

2023-06-19 02:04 UTC, jackey8616 commented on src/order/order.controller.spec.ts
> +    application.close();
await application.close();

2023-06-19 02:04 UTC, jackey8616 commented on src/order/order.controller.spec.ts
> +    it('should orderId is invalid', async () => {
`Should raise error due to orderId is not found` ?

2023-06-19 02:04 UTC, jackey8616 commented on src/order/order.controller.spec.ts
> +    it('should order received transfer success', async () => {
`Should transfer received order successfully` ?

2023-06-19 02:04 UTC, jackey8616 commented on src/order/order.controller.spec.ts
> +      const orderDataToken = await sign(orderData, process.env.HASURA_JWT_SECRET, {
```ts
describe('OrderController (e2e)', () => {
  let configService: ConfigService<{HASURA_JWT_SECRET: string; }>;
  ...
  beforeEach(async () => {
    ...
    application = module.createNestApplication();
    configService = application.get<ConfigService<{ HASURA_JWT_SECRET: string}>>(ConfigService);
    await application.init();
    ...
  });

  ...

  it('should order received transfer success', async () => {
    ...
    const orderDataToken = await sign(orderData, configService.get('HASURA_JWT_SECRET'), {
        expiresIn: '30days',
    });
    ...
  });
});
```

2023-06-19 02:04 UTC, jackey8616 commented on src/order/order.controller.ts
> +  path: 'order',
`orders` ?

2023-06-19 17:53 UTC, aniku777tw commented on src/order/order.controller.spec.ts
> +appSecret.value = 'testKey';
updated

2023-06-19 17:57 UTC, aniku777tw commented on src/order/order.controller.spec.ts
> +  beforeAll(async () => {
updated

2023-06-19 17:58 UTC, aniku777tw commented
updated

2023-06-20 02:50 UTC, jackey8616 requested changes

2023-06-20 02:50 UTC, jackey8616 commented on src/order/order.controller.spec.ts
> +describe('OrderController (e2e)', () => {
Can organize like [this](https://github.com/urfit-tech/lodestar-server/blob/feature/update-group-buying-order-log/test/auth.e2e-spec.ts#L29).

2023-06-20 02:50 UTC, jackey8616 commented on src/order/order.controller.spec.ts
> +    manager = application.get<EntityManager>('phdbEntityManager');
`manager = application.get<EntityManager>('phdbEntityManager');`  

Cange to

`manager = application.get<EntityManager>(getEntityManagerToken('phdb'));`

2023-06-21 03:41 UTC, jackey8616 approved these changes
LGTM.

2023-06-21 03:42 UTC, merged