feat: track program content progress
urfit-tech/lodestar-server pull request #197
Opened 2024-06-17 03:31 UTC by TedxTed

# Track program progress api 

- routes : `/api/v2/programs/:programId/content/:programContentId/track-process`
- params : 
```json
{
  "progress": 0.6,
  "lastProgress": 0.677777777
}
```
- response 
  - success: {status: ok}
  - fail:   
  ```json
  {
    "code": "TRACK_PROGRESS_FAILED",
    "message": "Failed to track program content progress",
    "result": "error.message"
  }
   ```

2024-06-19 09:46 UTC, TedxTed commented
![](https://github.trello.services/images/mini-trello-icon.png) [(5)【學習進度】歷程記錄、報表分析、我的課程主頁，三處的學習進度不一致(治根卡)](https://trello.com/c/eWiG9Ue4/5130-5%E3%80%90%E5%AD%B8%E7%BF%92%E9%80%B2%E5%BA%A6%E3%80%91%E6%AD%B7%E7%A8%8B%E8%A8%98%E9%8C%84%E3%80%81%E5%A0%B1%E8%A1%A8%E5%88%86%E6%9E%90%E3%80%81%E6%88%91%E7%9A%84%E8%AA%B2%E7%A8%8B%E4%B8%BB%E9%A0%81%EF%BC%8C%E4%B8%89%E8%99%95%E7%9A%84%E5%AD%B8%E7%BF%92%E9%80%B2%E5%BA%A6%E4%B8%8D%E4%B8%80%E8%87%B4%E6%B2%BB%E6%A0%B9%E5%8D%A1)

2024-07-08 15:06 UTC, clothe09986 approved these changes

2024-07-08 15:06 UTC, clothe09986 commented on src/program/program.controller.ts
> +      });
I think  it's better to have  a consistent response format for our API. Here the success and error responses are not following the same structure, which might cause confusion for the front-end developers.

2024-07-08 15:06 UTC, clothe09986 commented on src/program/program.service.ts
> +    }
can be shorter
ex:  just use `!memberId`

2024-07-08 15:07 UTC, clothe09986 requested changes
resolve the conflicts

2024-07-26 09:05 UTC, clothe09986 approved these changes

2024-07-26 09:05 UTC, merged