Feat/coin post controller import
urfit-tech/lodestar-server pull request #228
Opened 2024-11-03 13:33 UTC by LoisChen68

2024-11-11 07:48 UTC, LoisChen68 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3)【代幣管理】希望後台可匯入代幣](https://trello.com/c/FEwfh5qy/5493-3%E3%80%90%E4%BB%A3%E5%B9%A3%E7%AE%A1%E7%90%86%E3%80%91%E5%B8%8C%E6%9C%9B%E5%BE%8C%E5%8F%B0%E5%8F%AF%E5%8C%AF%E5%85%A5%E4%BB%A3%E5%B9%A3)

2024-11-13 08:43 UTC, TedxTed requested changes

2024-11-13 08:43 UTC, TedxTed commented on src/coin/coin.service.ts
> +    const deserialized = rawRows.map((rawRow) => new CsvRawCoin().deserializedFromCsvRawRow(headerInfos, rawRow));
目的 ： 將csv row 封裝成 dto
1.  `new CsvRawCoin().deserializedFromCsvRawRow` 這個做法比較偏向是使用類別方法去實作，而不是實體方法，透過類別方法去建構實體
2. 而oop強調的是 既然已存在此個體，這個體必有其原生的屬性(ex:身而為人，我出身自是男性，台北人），這觀念會靠 constructor 去處理屬性的問題，也就是要靠new的時候去注入他原生的屬性
4. 透過constructor 去注入屬性本身就會驗證是否正確

這邊的處理建議這樣
```typescript
new CsvRawCoin({
  email: header.email,
  title: header.title,
});
// class 
class CsvRawCoin {
  constructor({ email, title }) {
    this.email = parseFieldFromRaw(email);
    this.title = parseFieldFromRaw(title);
  }
}
```

2024-11-22 03:52 UTC, TedxTed commented
對於 `importer tasker` 有幾個建議

1. single responsibility 談的是 一個類別只對一個使用者或利益負責，目前importer tasker有兩個使用者(1) member importer (2) coin importer 勢必其需要分成兩個不同類別
2. 若是走oop, 那可以這樣想 執行者(instance) 呼叫 做什麼事情(方法）,  member 跟 coin 雖然都是 呼叫 import(方法） , 但執行者不同那意義也不同，就像是 老師跟學生都要上課，老師(instance) 呼叫 上課(方法） 跟 學生(instance) 呼叫 上課(方法）意義不同
3. oop下要不斷的思考 誰(instance) 執行了 什麼(方法）
4. 依據 2 , 兩個都有 “上課” 的方法，那可以把他抽象出來 ，依據產生的實體，都去執行上課的方法（工廠模式）
5. 依據 2 學生和老師去上課時 都要走到教室，都要坐到位置，都要打開課本 ... 這些一樣的事情也可以抽象出來 ( 樣板方法）

2024-11-25 02:55 UTC, TedxTed commented on src/coin/coin.service.ts
> +    const deserialized = rawRows.map((rawRow) => new CsvRawCoin().deserializedFromCsvRawRow(headerInfos, rawRow));
第一種

```typescript
// class 
class CsvRawCoin {
  constructor({ email, title }) {
    this.email = parseFieldFromRaw(email);
    this.title = parseFieldFromRaw(title);
  }
}

const instance = new CsvRawCoin({
  email: header.email,
  title: header.title,
});

validate(instance)
```
第二種
```typescript
class CsvRawCoin {
}
 
const instance = new CsvRawCoin()
instance.email = parseFieldFromRaw('someEmail');
instance.title =  parseFieldFromRaw(title);

validate(instance)
```


第三種
```typescript
class CsvRawCoin {
  static validateCoin(coin) {
       // 更多validate處理方式
       validate(instance)
   }
}
 
const instance = new CsvRawCoin()
instance.email = parseFieldFromRaw('someEmail');
instance.title =  parseFieldFromRaw(title);

CsvRawCoin.validateCoin(instance)
```

2024-11-29 09:06 UTC, TedxTed approved these changes

2024-11-29 09:06 UTC, TedxTed approved these changes

2024-11-29 09:07 UTC, merged

2024-12-18 04:04 UTC, kkshyu commented on src/coin/coin.service.ts
> +    const deserialized = rawRows.map((rawRow) => new CsvRawCoin().deserializedFromCsvRawRow(headerInfos, rawRow));
1. new Clz({ title: 'xxx' }) -> instance
2. new Clz().clone({ title: 'xxx' }) / instance.clone()
3. Clz.createFromRow({ title: 'xxx' })

```
class Clz:
     q = 1
     foo(self):
         // self.q 
         return new Clz()
     @staticmethod
     bar():
          // self x
          return new Clz()

instance = new Clz()
instance2 = instance.foo()

instance2 = Clz.foo(instance1)
```

2024-12-18 04:30 UTC, kkshyu commented
class Tasker {
    abstract
    process() {}
}
class ImporterTasker extends Tasker {
    process() {
       new CoinImporter().import()
       new MemberImporter().import()
    }
}
class BaseImporter {
    abstract
    import() {}
}
class CoinImporter extends BaseImporter {}  // implement import()
class MemberImporter extends BaseImporter {}  // implement import()

// PorterRunner
// MailTasker