feat: generate tmp password & save in redis
urfit-tech/lodestar-server pull request #55
Opened 2023-08-23 18:01 UTC by clothe09986

2023-08-24 03:37 UTC, clothe09986 commented
![](https://github.trello.services/images/mini-trello-icon.png) [【帳戶】萬能密碼改版為申請制](https://trello.com/c/4yhzEW7H/4589-%E3%80%90%E5%B8%B3%E6%88%B6%E3%80%91%E8%90%AC%E8%83%BD%E5%AF%86%E7%A2%BC%E6%94%B9%E7%89%88%E7%82%BA%E7%94%B3%E8%AB%8B%E5%88%B6)

2023-09-19 03:06 UTC, jackey8616 requested changes

2023-09-19 03:06 UTC, jackey8616 commented on src/auth/auth.controller.ts
> +      await this.authService.insertAuthAuditLog(applicant, memberData[0].id, purpose);
Controller should not contains business logics.

2023-09-19 03:06 UTC, jackey8616 commented on src/entity/PermissionGroup.ts
> +import { MemberPermissionGroup } from '../member/entity/member_permission_group.entity';
`'~/member/entity/member_permission_group.entity'`

2023-09-19 03:06 UTC, jackey8616 commented on src/entity/index.ts
> +import { MemberPermissionGroup } from '../member/entity/member_permission_group.entity';
'~/member/entity/member_permission_group.entity'

2023-09-19 03:06 UTC, jackey8616 commented on src/member/entity/member_permission_group.entity.ts
> +import { PermissionGroup } from '../../entity/PermissionGroup';
`~/entity/PermissionGroup'`

2023-09-19 03:06 UTC, jackey8616 commented on test/auth.e2e-spec.ts
> -    // });
I want my comment back.

2023-09-19 03:06 UTC, jackey8616 commented on test/auth.e2e-spec.ts
> +    it('should fail to retrieve a temporary password', async () => {
'should fail to retrieve a temporary password'
-> Describe with situation
e.g.: 'Should fail due to ......'

2023-09-19 03:06 UTC, jackey8616 commented on test/auth.e2e-spec.ts
> +    it('should insert an audit log', async () => {
Combine with success cases.

2023-09-19 03:06 UTC, jackey8616 commented on test/auth.e2e-spec.ts
> +    it('should insert the temporary password into Redis', async () => {
Combine with success cases.

2023-09-19 03:06 UTC, jackey8616 commented on src/auth/auth.type.ts
> +export interface GenerateTmpPasswordDto {
DTO.

2023-09-19 05:02 UTC, clothe09986 commented on src/auth/auth.controller.ts
> +      await this.authService.insertAuthAuditLog(applicant, memberData[0].id, purpose);
fixed

2023-09-19 05:10 UTC, jackey8616 approved these changes

2023-09-19 05:10 UTC, merged