Feature/porter runner migrate to server refactor
urfit-tech/lodestar-server pull request #92
Opened 2023-11-20 01:22 UTC by TedxTed

migrate backend porter runner to server 

## Key Changes
### heartbeat check
### Porting Last Logged In Data:
 - Added functionality to retrieve and update the last login timestamps of users from cached data.
 ### Porting Player Event Data:
 - retrieve player event data from the cache and store it in the database
 ### Porting Podcast Program Data
- extracting podcast program progress data from the cache and storing it in the database.

## others
- Batch Processing Logic

2023-11-20 02:30 UTC, Ponchimeow commented
![](https://github.trello.services/images/mini-trello-icon.png) [(2)【歷程記錄】會員觀看課程我的主頁進度條與歷程不同步](https://trello.com/c/m2cECZmJ/4820-2%E3%80%90%E6%AD%B7%E7%A8%8B%E8%A8%98%E9%8C%84%E3%80%91%E6%9C%83%E5%93%A1%E8%A7%80%E7%9C%8B%E8%AA%B2%E7%A8%8B%E6%88%91%E7%9A%84%E4%B8%BB%E9%A0%81%E9%80%B2%E5%BA%A6%E6%A2%9D%E8%88%87%E6%AD%B7%E7%A8%8B%E4%B8%8D%E5%90%8C%E6%AD%A5)

2023-11-23 02:26 UTC, aniku777tw requested changes

2023-11-23 02:26 UTC, aniku777tw commented on src/runner/porter.runner.ts
> +          programContentLog.playbackRate = value.playbackRate;
if playback rate not exist, please default this value by 1

2023-11-23 02:26 UTC, aniku777tw commented on src/runner/porter.runner.ts
> +        const [, memberId, , programContentId] = key.split(':');
we have the key created time (unix) in cache key, use
```
const [, memberId, , podcastProgramId, createdAt ] = key.split(':');
```
and use this ```createdAt``` to insert program content log

2023-11-23 02:26 UTC, aniku777tw commented on test/runner/porter_runner.e2e-spec.ts
> +  afterAll(async () => {
delete all data before close app
```
    await programPlanRepo.delete({});
    await currencyRepo.delete({});
    await programContentLogRepo.delete({});
    await programContentProgressRepo.delete({});
    await programContentRepo.delete({});
    await programContentSectionRepo.delete({});
    await programContentBodyRepo.delete({});
    await programRepo.delete({});
    await podcastProgramProgressRepo.delete({});
    await podcastProgramRepo.delete({});
    await podcastAlbumRepo.delete({});
    await memberRepo.delete({});
    await appSettingRepo.delete({});
    await appSecretRepo.delete({});
    await appHostRepo.delete({});
    await appRepo.delete({});
    await appPlanRepo.delete({});
    await roleRepo.delete({});
```

2023-11-23 02:26 UTC, aniku777tw commented on src/runner/porter.runner.ts
> +        await manager.update(Member, memberId, { loginedAt });
In my opinion to create a method in MemberInfra.ts  is better

2023-11-23 02:26 UTC, aniku777tw commented on src/runner/porter.runner.ts
> +        await manager.findOne(Member, { where: { id: memberId } });
unnecessary query

2023-11-23 02:26 UTC, aniku777tw commented on src/runner/porter.runner.ts
> +          const programContent = await programContentRepo.findOneBy({ id: programContentId });
create a ```programContentLogInfra.ts``` to handle will be more reusable

2023-11-23 02:26 UTC, aniku777tw commented on src/runner/porter.runner.ts
> +        });
same thing as above

2023-11-23 02:26 UTC, aniku777tw commented on src/runner/porter.runner.ts
> +          podcastProgramProgress = manager.getRepository(PodcastProgramProgress).create(info);
same thing as above

2023-11-23 02:26 UTC, aniku777tw commented on test/runner/porter_runner.e2e-spec.ts
> +
please clear redis cache before close app

2023-11-24 07:23 UTC, TedxTed commented on src/runner/porter.runner.ts
> +          const programContent = await programContentRepo.findOneBy({ id: programContentId });
Sure, I'll use the existing program.infra.ts to implement it first, if you think it is not proper, I'll make programcontent.infra independently.

2023-11-24 07:25 UTC, TedxTed commented on src/runner/porter.runner.ts
> +        await manager.findOne(Member, { where: { id: memberId } });
yes, you are right , the query to find the member after updating it is unnecessary. I'll remove it , thanks

2023-11-24 07:26 UTC, TedxTed commented on src/runner/porter.runner.ts
> +        await manager.update(Member, memberId, { loginedAt });
sure , i will move crud to infra ～

2023-11-24 07:28 UTC, TedxTed commented on test/runner/porter_runner.e2e-spec.ts
> +
ok , i add `await cacheService.getClient().flushall();` to `afterEach` hook

2023-11-24 07:29 UTC, TedxTed commented on test/runner/porter_runner.e2e-spec.ts
> +  afterAll(async () => {
ok ,  I'll include this in the `afterEach` hook

2023-11-24 07:33 UTC, TedxTed commented on src/runner/porter.runner.ts
> +        const [, memberId, , programContentId] = key.split(':');
ok , I'll used the created time from the cache key~

2023-11-29 01:54 UTC, clothe09986 commented
![](https://github.trello.services/images/mini-trello-icon.png) [【DC alert】將porter runner移到 lodestar-server，解決alert一直響](https://trello.com/c/1bPejRQh/4871-%E3%80%90dc-alert%E3%80%91%E5%B0%87porter-runner%E7%A7%BB%E5%88%B0-lodestar-server%EF%BC%8C%E8%A7%A3%E6%B1%BAalert%E4%B8%80%E7%9B%B4%E9%9F%BF)

2023-12-13 02:24 UTC, aniku777tw approved these changes

2023-12-13 03:01 UTC, merged

2023-12-20 06:39 UTC, kkshyu commented on src/runner/porter.runner.ts
> +        const [, memberId, , programContentId] = key.split(':');
add a comment like 
```
// key format:  `program-content:{memberId}:XXXX:{podcastProgramId}:createdAt`
```