[WIP] Handle meta webhook
urfit-tech/lodestar-server pull request #98
Opened 2023-12-01 04:01 UTC by shana0440

This PR add webhook endpoint, to store and retrieve meta lead-ads.

2023-12-11 02:40 UTC, clothe09986 commented
![](https://github.trello.services/images/mini-trello-icon.png) [【外包reivew】Calendar & Meta Lead Ad](https://trello.com/c/SVlmsVxO/4938-%E3%80%90%E5%A4%96%E5%8C%85reivew%E3%80%91calendar-meta-lead-ad)

2023-12-15 03:06 UTC, clothe09986 reviewed
Please add the e2e testing,thanks.

2023-12-17 21:23 UTC, shana0440 commented
@clothe09986  Updated.

2023-12-21 14:10 UTC, clothe09986 requested changes

2023-12-21 14:10 UTC, clothe09986 commented on src/webhooks/meta/lead.service.ts
> +      廣告組合: 'ad_name',
These two are written in reverse.

2023-12-21 14:12 UTC, clothe09986 commented
Please resolve conflicts first, thanks.

2023-12-21 20:22 UTC, shana0440 commented
@clothe09986 Updated, thanks.

2023-12-22 04:56 UTC, clothe09986 approved these changes

2024-02-24 09:36 UTC, merged